PERIOD_WEEKLY = 'Weekly'
PERIOD_BIWEEKLY = 'Bi-Weekly'
PERIOD_SEMIMONTHLY = 'Semi-Monthly'
PERIOD_MONTHLY = 'Monthly'
PERIOD_QUARTERLY = 'Quarterly'
PERIOD_ANNUALLY = 'Annually'
PERIOD_PERDIEM = 'Per Diem'

PAY_PERIODS = [PERIOD_WEEKLY, PERIOD_BIWEEKLY, PERIOD_SEMIMONTHLY, PERIOD_MONTHLY, PERIOD_QUARTERLY, PERIOD_ANNUALLY, PERIOD_PERDIEM]
